version: "3.8"

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: order-renewal
    volumes:
      - ./master/my.cnf:/etc/mysql/my.cnf
      - ./master/data:/var/lib/mysql
      - ./master/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

  mysql-slave-1:
    image: mysql:8.0
    container_name: mysql-slave-1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: order-renewal
    volumes:
      - ./slave/my.cnf:/etc/mysql/my.cnf
      - ./slave/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3307:3306
    depends_on:
      - mysql-master

  marketboro-mysql-phpmyadmin:
    depends_on:
      - mysql-master
    image: phpmyadmin/phpmyadmin
    container_name: marketboro-mysql-phpmyadmin
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysql-master
      MYSQL_ROOT_PASSWORD: password
    platform: linux/amd64
    restart: always
