version: '3.8'

networks:
  default:
    name: order-renewal

volumes:
  data:
    driver: local
  config:
    driver: local

services:
  order-renewal-mysql:
    image: mysql:latest
    container_name: order-renewal-mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: order-renewal
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: order
      MYSQL_PASSWORD: password
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/amd64
    restart: always

  order-renewal-mysql-phpmyadmin:
    depends_on:
      - order-renewal-mysql
    image: phpmyadmin/phpmyadmin
    container_name: order-renewal-mysql-phpmyadmin
    ports:
      - 8082:80
    environment:
      PMA_HOST: order-renewal-mysql
      MYSQL_ROOT_PASSWORD: password
    platform: linux/amd64
    restart: always

  order-renewal-redis:
    image: redis
    container_name: order-renewal-redis
    ports:
      - 6379:6379

  order-renewal-application:
    build: .
    environment:
      - MYSQL_HOST=order-renewal-mysql
      - REDIS_HOST=order-renewal-redis
      - SPRING_ACTIVE_PROFILE=local
    ports:
      - 8080:8080
    depends_on:
      - order-renewal-mysql
      - order-renewal-redis
    container_name: order-renewal-application
    restart: on-failure