version: '3.8'

networks:
  default:
    name: come-us

volumes:
  data:
    driver: local
  config:
    driver: local

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/nginx/auth/minica.pem:/user/apps/nginx/minica.pem
      - ./infra/nginx/auth/minica-key.pem:/user/apps/nginx/minica-key.pem
    ports:
      - 80:80
      - 443:443
    depends_on:
      - come-us-application1
      - come-us-application2

  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: come-us
      TZ: Asia/Seoul
    volumes:
      - ./infra/mysql-replication/master/my.cnf:/etc/mysql/my.cnf
      - ./infra/mysql-replication/master/data:/var/lib/mysql
      - ./infra/mysql-replication/master/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  mysql-slave-1:
    image: mysql:8.0
    container_name: mysql-slave-1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: come-us
      TZ: Asia/Seoul
    volumes:
      - ./infra/mysql-replication/slave/my.cnf:/etc/mysql/my.cnf
      - ./infra/mysql-replication/slave/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    depends_on:
      - mysql-master

  mysql-phpmyadmin:
    depends_on:
      - mysql-master
    image: phpmyadmin/phpmyadmin
    container_name: mysql-phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql-master
      MYSQL_ROOT_PASSWORD: password
    restart: always

  redis-node1:
    platform: linux/x86_64 # m1 MacOS의 경우
    image: redis:6.2
    container_name: redis-node1
    volumes: # 작성한 설정 파일을 볼륨을 통해 컨테이너에 공유
      - ./infra/redis-cluster/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6380:6380"
      - "6381:6381"
      - "6379:6379"

  redis-node2:
    network_mode: "service:redis-node1"
    platform: linux/x86_64
    image: redis:6.2
    container_name: redis-node2
    volumes:
      - ./infra/redis-cluster/redis1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node3:
    network_mode: "service:redis-node1"
    platform: linux/x86_64
    image: redis:6.2
    container_name: redis-node3
    volumes:
      - ./infra/redis-cluster/redis2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-cluster-entry:
    network_mode: "service:redis-node1"
    platform: linux/x86_64
    image: redis:6.2
    container_name: redis-cluster-entry
    command: redis-cli --cluster create 127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381 --cluster-yes
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
    restart: on-failure

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis-node1:6379
    ports:
      - "8087:8081"
    platform: linux/x86_64
    restart: always

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=S3
      - DEFAULT_REGION=ap-northeast-2
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=1

  come-us-application1:
    image: ${APPLICATION_IMAGE}
    environment:
      - MYSQL_HOST=mysql-master
      - REDIS_HOST1=redis-node1
      - REDIS_HOST2=redis-node2
      - REDIS_HOST3=redis-node3
      - AWS_ENDPOINT=localstack
      - SPRING_ACTIVE_PROFILE=local
    ports:
      - 8080:8080
    depends_on:
      - mysql-master
      - mysql-slave-1
      - redis-node1
      - redis-node2
      - redis-node3
      - localstack
    container_name: come-us-application1
    restart: on-failure

  come-us-application2:
    image: ${APPLICATION_IMAGE}
    environment:
      - MYSQL_HOST=mysql-master
      - REDIS_HOST1=redis-node1
      - REDIS_HOST2=redis-node2
      - REDIS_HOST3=redis-node3
      - AWS_ENDPOINT=localstack
      - SPRING_ACTIVE_PROFILE=local
    ports:
      - 8081:8081
    depends_on:
      - mysql-master
      - mysql-slave-1
      - redis-node1
      - redis-node2
      - redis-node3
      - localstack
    container_name: come-us-application2
    restart: on-failure



