spring:
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:password}
        jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:order-renewal}?rewriteBatchedStatements=true
    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:password}
        jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/${MYSQL_DATABASE:order-renewal}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  redis:
    cluster:
      nodes:
        - ${REDIS_HOST1:localhost:6379}
        - ${REDIS_HOST2:localhost:6380}
        - ${REDIS_HOST3:localhost:6381}

jwt:
  issuer: order-renewal
  access-token:
    header: access-token
    expiry-seconds: ${ACCESS_EXPIRY_SECOND:ENC(43VpAPQWzFtX6I2vbopM+Q==)}
  refresh-token:
    header: refresh-token
    expiry-seconds: ${REFRESH_EXPIRY_SECOND:ENC(jGxk7kBP4xV+MkSyHX/Sjg==)}
  secret-key: ${SECRET_KEY:ENC(E9Of+Ca7DdsBBGMfwKam9M7ty9QsAvgw)}

security:
  url-pattern-config:
    ignoring:
      GET:
        - /v3/api-docs/**
        - /swagger-ui/**
        - /swagger-ui.html/**
        - /health
        - /api/products/*
        - /api/products
        - /test/**
      POST:
        - /api/auth/login
        - /api/users
        - /test/**
      PATCH: [ ]
      PUT: [ ]
      DELETE: [ ]
    permit-all:
      GET: [ ]
      POST: [ ]
      PATCH: [ ]
      PUT: [ ]
      DELETE: [ ]
      OPTIONS: /**

cookie:
  secure: ${COOKIE_SECURE:false}
  same-site: ${COOKIE_SAME_SITE:lax}
  domain: ${DOMAIN:localhost}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY:test}
      secretKey: ${AWS_SECRET_KEY:test}
    s3:
      bucket: ${S3_BUCKET:renewal-commerce-local}
      suffix-url: ${S3_SUFFIX_URL:https://renewal-commerce-local.s3.ap-northeast-2.amazonaws.com/}
      endpoint: ${AWS_ENDPOINT:http://127.0.0.1:4566}
    stack:
      auto: false
    region:
      static: ${STATIC_REGION:ap-northeast-2}

encryptor:
  key: ${ENCRYPTOR_KEY:order-renewal}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace