spring:
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
        jdbc-url: ${MYSQL_JDBC_MASTER_URL}
    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
        jdbc-url: ${MYSQL_JDBC_SLAVE_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  redis:
    cluster:
      nodes:
        - ${REDIS_HOST1}
        - ${REDIS_HOST2}
        - ${REDIS_HOST3}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${OAUTH_K_CLIENT_ID}
            client-secret: ${OAUTH_K_CLIENT_SECRET}
            scope: ${OAUTH_K_SCOPE}
            redirect-uri: $${REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


jwt:
  issuer: ${ISSUER}
  access-token:
    header: ${ACCESS_TOKEN_HEADER}
    expiry-seconds: ${ACCESS_EXPIRY_SECOND}
  refresh-token:
    header: ${REFRESH_TOKEN_HEADER}
    expiry-seconds: ${REFRESH_EXPIRY_SECOND}
  secret-key: ${SECRET_KEY}

security:
  url-pattern-config:
    ignoring:
      GET:
        - /v3/api-docs/**
        - /swagger-ui/**
        - /swagger-ui.html/**
        - /health
        - /api/products/*
        - /api/products
        - /api/reviews/*
        - /api/rankings/*
      POST:
        - /api/auth/login
        - /api/users
        - /test/**
      PATCH: [ ]
      PUT: [ ]
      DELETE: [ ]
    permit-all:
      GET: [ ]
      POST: [ ]
      PATCH: [ ]
      PUT: [ ]
      DELETE: [ ]
      OPTIONS: /**

cookie:
  secure: ${COOKIE_SECURE}
  same-site: ${COOKIE_SAME_SITE}
  domain: ${DOMAIN}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
      suffix-url: ${S3_SUFFIX_URL}
    stack:
      auto: false
    region:
      static: ${STATIC_REGION}

encryptor:
  key: ${ENCRYPTOR_KEY}